include:
  - ../postgres/docker-compose.yml
services:
  task-service:
    build:
      context: ../
      dockerfile: task-service/Dockerfile
    volumes:
      - ../shared:/var/www/shared
    depends_on:
      - postgres
    container_name: task-service
    ports:
      - "8002:8000"
    # entrypoint: ["sh","-c", "sleep 30 && php /var/wwww/artisan migrate && php /var/www/artisan serve --host 0.0.0.0 --port 8000"]

