include:
  - ../postgres/docker-compose.yml
services:
  task-service:
    build:
      context: ../
      dockerfile: task-service/Dockerfile
    volumes:
      - ../shared:/var/www/shared
    depends_on:
      - postgres
    container_name: task-service
    ports:
      - "8002:8000"

