services:
  postgres:
    image: postgres:15.8-alpine3.20
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: "root"
    volumes:
      - ./.docker/postgres:/var/lib/postgresql/data
